### PR TITLE
fix: store correct date time

### LINKED ISSUE #62: Problem with date input, entries are not UTC
React Json Schema for input for `date-time` use `datetime-locale` type input, so data stored from this input is locale

### PR DESCRIPTION
**Pull request by foyarash**
Fixes #62

Also includes formatting of the whole project with prettier

### CODE REVIEW

File: apps/example/pages/admin/[[...nextadmin]].tsx [hunk 1]
```diff
@@ -37,22 +39,23 @@ const options: NextAdminOptions = {
...
           birthDate: {
-            format: "date",
-            handler: {
-              //This getter is used to format the date in the form and match with the format of the input
-              get: (value) => {
-                return value?.toISOString().split("T")[0];
-              },
-            }
-          }
+            format: "date-time",
```
Comment (colin27091) [inline apps/example/pages/admin/[[...nextadmin]].tsx:42]: You should leave `date` as `format`

**Review by colin27091 — APPROVED** [review]
